
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-docker-kubernetes-gke
  labels:
    app: jenkins-docker-kubernetes-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-docker-kubernetes-gke
  template:
    metadata:
      labels:
        app: jenkins-docker-kubernetes-gke
    spec:
      containers:
        - name: jenkins-docker-kubernetes-gke
          image: stephenrajisac/jenkins-docker-kubernetes-gke:tagversion
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-docker-kubernetes-gke
spec:
  type: LoadBalancer
  selector:
    app: jenkins-docker-kubernetes-gke
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080